EXEC job.sp_SEL_TAGS_PLANTA_HISTORIZA 2
--EXEC sp_rename 
--    'job.sp_SEL_TAGS_PLANTA_SELECT_HISTORIZA',
--    'sp_SEL_TAGS_PLANTA_HISTORIZA';

ALTER PROCEDURE job.sp_SEL_TAGS_PLANTA_HISTORIZA
@ID_PLANTA INT
AS
BEGIN
    SELECT ID_TAG,TAG,ID_PLANTA,ATRIBUTO,TAG_NOMBRE,TAG_PCO_MII
    FROM dbo.TAGS
    WHERE 
    ID_PLANTA=@ID_PLANTA
    AND
    FLG_VIGENTE_TAG='1'
    AND 
    FLG_HISTORIZA='1';
END;
GO